image: docker.gamechanger.io/go1.3.1
git:
  depth: 10
env:
  - REPO=/var/cache/drone/src/github.com/gamechanger/dog-devolver
script:
  - mv $REPO $GOPATH/src/github.com/gamechanger
  - cd $GOPATH/src/github.com/gamechanger/dog-devolver
  - godep restore
  - go build -v
  - go test -v
  - go vet
  - errcheck -blank -ignore "[p|P]roxyTo*|Close|[wW]rite.*|[rR]ead.*" $(go list ./...)
  - tests_complete dog-devolver
notify:
  webhook:
    urls:
      - http://localhost:7777/webhook
    on_success: true
    on_failure: true
