image: docker.gamechanger.io/go1.3.1
git:
  depth: 10
env:
  - REPO=/var/cache/drone/src/github.com/gamechanger/dog-devolver
script:
  - cd $REPO
  - godep restore
  - go build -v
  - go test -v
  - go vet
  - errcheck -ignore 'Close|[wW]rite.*|[rR]ead.*' -blank github.com/gamechanger/dog-devolver
  - tests_complete dog-devolver
notify:
  webhook:
    urls:
      - http://localhost:7777/webhook
    on_success: true
    on_failure: true
